baseURL = "http://example.org/"
languageCode = "en-us"
title = "Greenhorn Tide"
theme = "hugo-theme-docdock-1.1"
contentDir = "content/march-2021"
enableRobotsTXT = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 3       
    ordered = true
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true    