baseURL = "http://example.org/"
languageCode = "en-us"
title = "Greenhorn Tide"
theme = "hugo-theme-docdock-1.1"
contentDir = "content/march-2021"
enableRobotsTXT = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]
